name = "BeagleJulia"
version = "0.1.0"
authors = ["Demetrios Agourakis <agourakis82@gmail.com>"]

[deps]
HTTP = "cd3eb016-35fb-5094-929b-558a96fad6f3"
JSON3 = "0f8b85d8-7281-11e9-16c2-39a750bddbf1"
Random = "9a3f8284-a2c9-5f02-9a11-845980a1fd5c"
Dates = "ade2ca70-3891-5945-98fb-dc099432e06a"
PythonCall = "6099a3de-0908-4bc9-bfbd-4a8492156bfe"
Lux = "b2108857-7c20-44ae-9111-449ecde12c47"
Metal = "dde46c2f-1e7f-52f2-82a5-e403b0b38d09"
CUDA = "05236ef9-13de-1879-8b57-7ecac4aa787e"
Optimisers = "3bd65402-5787-11e9-1adc-39752487f4e2"
Zygote = "e88e6eb3-aa80-5325-afca-941959d7151f"
JLD2 = "033835bb-8acc-5ee8-8cdc-15bb4b2c3c56"
ComponentArrays = "b0b7db55-cfe3-40fc-9ded-daae3e21b5ea"
Graphs = "86223c79-3864-5bf0-83f7-82e309a1794f"
DifferentialEquations = "0c46a032-eb57-5973-a616-4ef871e96c7a"
ModelingToolkit = "961ee093-0014-501f-94e3-1adfb9401dc2"
Symbolics = "0c5d862f-8b57-4792-8d22-cc4d179c2569"
CSV = "336ed68f-0bac-5ca0-87d4-7b16caf5d00b"
DataFrames = "a93c6f00-e57d-5684-b7b6-d8193f3e46c0"
FFTW = "7a1cc6ca-52ef-59f5-83cd-3ff705d8c0ac"
Statistics = "10745b16-79ce-11e8-11f9-7d13ad32a3b2"
Optim = "429524aa-4258-5f27-9876-11c5f367c010"
ImageFiltering = "6a3955dd-da59-5bc1-801d-552bdd6616a7"
ImageSegmentation = "80713f1b-4b94-5b90-8195-419fb4c42664"
FileIO = "5789e2e9-d7fb-5bc7-8068-2c6fae9b9549"

[compat]
julia = "1.10"
